# Generated by Django 3.1.4 on 2021-01-14 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PUBLIC_CHAT', '0002_auto_20210114_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(help_text='Users who are connected to the chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
