# Generated by Django 3.1.4 on 2021-01-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_comment_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
