# Generated by Django 3.1.4 on 2021-01-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_auto_20210118_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comments',
        ),
    ]
